project:
  type: website
  output-dir: docs

website:
  title: "Kākāpō Industries"
  favicon: images/kakapo-logo.png
  navbar:
    logo: images/kakapo-logo.png
    left:
      - href: index.qmd
        text: Home
      - text: "Catchment groups"
        href: catchment-groups.qmd
    right: 
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

resources:
  - images/

