project:
  type: website
  output-dir: docs

website:
  title: "Kakapo Industries"
  favicon: images/kakapo-logo.png
  navbar:
    logo: images/kakapo-logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

