project:
  type: website
  output-dir: docs

website:
  title: "Kākāpō Industries"
  favicon: images/kakapo-logo.png
  page-footer: "© Copyright 2025, Kākāpō Industries" 
  navbar:
    logo: images/kakapo-logo.png
    left:
      - href: index.qmd
        text: Home
      - text: "3D topographic models"
        menu:
          - text: "Custom 3D models"
            href: 3d-models.qmd
          - text: "For catchment groups"
            href: catchment-groups.qmd
          - text: "For regional councils"
            href: regional-councils.qmd
          - text: "FAQs"
            href: faqs.qmd
    right: 
      - text: "Etsy Shop"
        icon: bag-heart
        href: https://www.etsy.com/nz/shop/KakapoIndustries
        target: _blank
      - href: about.qmd
        text: "About us"
      - href: contact.qmd
        text: "Contact us"

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    fontawesome: true

editor: visual

resources:
  - images/

